### ISSUE TITLE
After deleting paths, the site shows "Sorry, can't find info for that track" message.

### ISSUE THREAD

**Issue by BreakingPoint** [UnderMybrella/EternalJukebox#20]
### Description
When paths are deleted, the website cannot find the track anymore. If you remove the "d" parameter from the URL, the track is available again:

### Song
Working link:
https://eternal.abimon.org/jukebox_go.html?id=3tehrxZR8eaANHov4cEctL&sq=0&thresh=15

Not working link:
https://eternal.abimon.org/jukebox_go.html?id=3tehrxZR8eaANHov4cEctL&d=0,1,2,4,6,8,9,11,13,15,24,25,26,32,33,35,36,38,46,47,48,53,54,57,61,62,65,66,68,69,72,76,77,78,79,82,83,86,90,91,93,94,96,100,104,105,106,108,111,112,133,137,138,141,142,145,146,147,149,150,153,157,158,159,160,165,169,170,173,174,177,178,181,182,189,205,206,207,208,209,210,213,214,217,218,221,222,223,224,233,234,237,238,239,240,241,242,243,245,246,249,253,254,255,256,257,258,269,270,271,281,282,283,285,286,287,288,289,290,301,305,306,307,313,314,315,317,333,337,338,341,345,346,349,350,351,352,353,354,365,366,369,373,388,410,417,442,460,2216&sq=0&thresh=15

Another example:

Working:
https://eternal.abimon.org/jukebox_go.html?id=5smUyJcGZB0FhJWUDhre7T&sq=0&thresh=20&bp=40,60,9

Not working:
https://eternal.abimon.org/jukebox_go.html?id=5smUyJcGZB0FhJWUDhre7T&d=6,7,136,144,500,504,516,520,550,563&sq=0&thresh=20&bp=40,60,9

**Comment by UnderMybrella** [comment]
Hey, sorry about the late response, last week or so has been a bit all over the place.

This issue is one that *may* (or may not) have existed even in the Infinite Jukebox, but I'm not sure. It basically boiled down to the parsing of parameters for the `d` tag declaring a phony `id` variable, which conflicted with the variable that holds the ID of the track in question. Shenanigans ensue, and the page tries to load a track with the last number in the `d` tag as the ID (so, in this case, 2216). Since that's not a valid ID, the webserver responses with a 404, and you're unable to load the track.

This should be fixed as of 1226327, and should be live on the site now.
