### ISSUE TITLE
The song that plays in the jukebox isn't the same song that plays in Spotify

### ISSUE THREAD

**Issue by deathaplenty** [UnderMybrella/EternalJukebox#23]
### Description
Some songs I've looked up in the jukebox are not the same songs that play in Spotify. I've opened the songs in Spotify and copied the ID from Spotify and pasted it into the Jukebox URL, so I know that it is the same song ID.

### Song
https://eternal.abimon.org/jukebox_go.html?id=7KTajhYNB0zLnirtch17au

https://eternal.abimon.org/jukebox_go.html?id=10jA9dUwDwNSljMj6eY9U5

### Additional Information
Spotify links for easy access:
Vi Och Olle:
https://open.spotify.com/track/7KTajhYNB0zLnirtch17au

Head Like I/O:
https://open.spotify.com/track/10jA9dUwDwNSljMj6eY9U5

**Comment by UnderMybrella** [comment]
Currently, the issue is that Spotify does not provide a way to obtain the audio for each track. The solution employed by the Eternal Jukebox at the moment is to do a Youtube search for the song title, and play that. Sometimes, these won't be the same songs (Additional filtering is being done on the rewrite branch for more fine tuning), and so you're able to tune it to a different URL. For your first link, you should find [this](https://eternal.abimon.org/jukebox_go.html?id=7KTajhYNB0zLnirtch17au&audio=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DNjwp-Sil-u0) to be an appropriate track I think?

**Comment by deathaplenty** [comment]
Ah, okay. Thanks for the info. :)
