### ISSUE TITLE
Beat Repeating??

### ISSUE THREAD

**Issue by MeggieTheWaffle** [UnderMybrella/EternalJukebox#25]
### Description
When I play, the first beat of the song keeps repeating

### Song
Any song

### Additional Information
I was trying to play Good Soldier by Flobots, if that works for you then it may be a problem on my end but I have no idea what it could possibly be.

**Comment by UnderMybrella** [comment]
This is almost *certainly* caused by pressing "control" which causes it to loop the beat it's on.
In addition, it happens if you use control tab to change the tab, the tab looses focus and the Jukebox treats it as if the control key is still being pressed.

Either press "control" again, or open the tuning window, press "Disable Keypresses", and reload.
I'll likely be changing this to be opt-in rather than opt-out in a later version, but for now those are your options.

**Comment by UnderMybrella** [comment]
Closing this because I haven't heard back and it sounds like a keypress issue.
