### ISSUE TITLE
Obscure songs will not load

### ISSUE THREAD

**Issue by Abeaker** [UnderMybrella/EternalJukebox#29]
### Description
Obscure artists do not load.
I do not have the technical expertise to actually break down what is happening but here are a few pictures of the console as I attempt to load a song.

1) https://imgur.com/a/TntkN

2) https://imgur.com/a/sUtyF

### Song

1) https://eternal.abimon.org/jukebox_go.html?id=3lGg3fPSPRpGqdudeC5dBY

2) https://eternal.abimon.org/jukebox_go.html?id=2ahW5IyuKcFCTnyV7gEvIC

### Additional Information
Popular songs do work. For example:
https://eternal.abimon.org/jukebox_go.html?id=6M14BiCN00nOsba4JaYsHW
Works just fine.
Cheers.

**Comment by UnderMybrella** [comment]
The source of this bug is a little more complicated than it might seem. It's less of an issue of popular vs obscure, as much as it is new audio is currently having issues being loaded. It sometimes works, and other times there's no chance.

*However* this issue has been fixed on the rewrite branch, as far as I can tell. I'll leave this open until those changes go live.
