### ISSUE TITLE
Unable to decode audio data

### ISSUE THREAD

**Issue by fromcj** [UnderMybrella/EternalJukebox#6]
### Description
Song Doesn't Play/Load

### Song
It's The End Of The World As We Know It - R.E.M.
https://eternal.abimon.org/jukebox_go.html?id=2oSpQ7QtIKTNFfA08Cy0ku

### Additional Information
All this info is from the dev console on Chrome

404s on GET https://eternal.abimon.org/song?id=2oSpQ7QtIKTNFfA08Cy0ku
Uncaught (in promise) DOMException: Unable to decode audio data jukebox_go.html?id=2oSpQ7QtIKTNFfA08Cy0ku:1
404s on GET https://eternal.abimon.org/popular_tracks?count=12 

All in that order

**Comment by UnderMybrella** [comment]
The 404 on song error is due to a bug with youtube-dl at the moment, something that is completely out of my hands (Current issue is over [here](https://github.com/rg3/youtube-dl/issues/13134))

The popular_tracks 404 is just due to me not updating the HTML call in the jukebox_go page, which doesn't affect anything since the call shouldn't even be there.

**Comment by UnderMybrella** [comment]
Patch should be live now, feel free to correct me if things stop working!

**Comment by fromcj** [comment]
Nope, all set, currently enjoying infinite R.E,M., thank you!

**Comment by UnderMybrella** [comment]
No problem! Glad you like it.
