### ISSUE TITLE
Hebrew songs don't work

### ISSUE THREAD

**Issue by barlubar** [UnderMybrella/EternalJukebox#73]
### Description
I've tried to use a Hebrew song I really like but it's showing me a blank page, I have tried this with several other Hebrew songs and I can say that the error is most likely related to the fact that the song is in Hebrew.

### Console Logs
![image](https://user-images.githubusercontent.com/65311408/81860164-08d05180-956f-11ea-89aa-d50e3e83646f.png)

### Song
https://eternalbox.dev/api/site/expand/3vi1AhWAA/redirect

**Comment by BoySanic** [comment]
Hey,

I don't think the fact the song is in Hebrew is what is causing this.

Can you send me the full link to the EternalBox page for it?

This might just be because the youtube API quota has been reached, in which case you'll need to manually supply your audio.

Can you also provide a screenshot of the 'blank' page you're seeing?

**Comment by barlubar** [comment]
here's the link:
https://eternalbox.dev/jukebox_go.html?id=6G9nY0aJNcQ8BHJjgRCgZ5

and here's the screenshot:
![image](https://user-images.githubusercontent.com/65311408/81870930-8ac87680-957f-11ea-91f4-008b4f59b141.png)

**Comment by BoySanic** [comment]
Hey,

This is definitely the youtube quota issue. It doesn't have anything to do with the song being Hebrew.

Please follow the steps below and let me know if this works for you:

![image](https://user-images.githubusercontent.com/26152620/81872844-99e00200-9548-11ea-868b-b1926f283b72.png)

**Comment by barlubar** [comment]
That fixed it! thank you!
